### ISSUE TITLE
Ufak öneriler :)

### ISSUE THREAD

**Issue by furkanesenn** [InFlames513/basit-yapay-zeka-apisi#1]
Dostum merhaba,

Yazmış olduğun kodun ve girişimin fazlasıyla hoşuma gitti. Fakat iznin olursa bazı önerilerim ve eleştirilerim olacaktı, mümkün müdür 😃

**Comment by InFlames513** [comment]
Tabiki

**Comment by InFlames513** [comment]
> Dostum merhaba,
> 
> Yazmış olduğun kodun ve girişimin fazlasıyla hoşuma gitti. Fakat iznin olursa bazı önerilerim ve eleştirilerim olacaktı, mümkün müdür 😃

tabiki

**Comment by furkanesenn** [comment]
Öncellikle fikrinden başlamak istiyorum, fikrin gayet güzel ve uygulanabilirliği yüksek. Bunu geliştirmek için belki bir sanal asistana bağlayabilirsin. Microsoft'un Cortana'sı, Amazon'un Alexa'sı, Google'ın Asistan'ı gibi asistanlar oluşturabilirsin kendine. Büyük ihtimalle "bu da yapay zeka mı ya" diyen ve yapay zeka hakkında gram bir şey bilmeyenler çıkacaktır projene yorum yapanlar arasından. Tabii sen bu "insancıklara" çok önem vermemen gerekiyor, yapay zekayı gerektiği kadar içeren bir proje olduğundan emin olabiliriz, konuyu az da olsa bilen birisi de zaten bu yorumu rahatlıkla yapabilir. 

Mesela şöyle bir şey yapabilirsin. Bu soru ve cevapların her biri veritabanında saklansın, oradan bu verileri çekelim. Veritabanı dediğimde irkilmene gerek yok, NoSQL olan bir veritabanı fazlasıyla işini görecektir (bkz: Google Firebase Realtime Database). Onun dışında bunu yapmana da gerek yok. Kendin JSON dosyası oluşturup, veri tabanı olarak kullanabilirsin. Ben bunu LUA üzerinde yapmıştım electraDB adı altında ve gayet de kullanılabilir halde şu anda.

Ayrıca mesela bir kullanıcı "nasılsınız" dedi, başka biri geldi "naber la" dedi başka biri de geldi "nörüyon" dedi. Bunların her birini kullanıcı dediğinde Data Training mantığı adı altında eğiterek yapay zekanın isabetliğini artırabilirsin. (bkz: https://www.youtube.com/watch?v=x2mRoFNm22g)

Onun dışında bunu bir bot haline getirebilirsin veya dediğim gibi sanal asistan haline getirebilirsin. Sanal asistan haline getirirsen ve mobil cihaz desteği vs. yaparsan çok iyi olabilir. Mesela kullanıcı mobil cihazını bilgisayarla eşleştirdikten sonra mobil cihazı üzerinden bilgisayar işlemleri yapabilsin. Ben buna benzer bir şeyi yapmıştım aslında. Telefonla bilgisayarı eşleştirip, telefon uygulaması üzerinden "yalnızca konuşarak" istediğimiz veya rastgele bir şarkının Spotify Windows aplikasyonu üzerinde çalmasını sağlayabiliyorduk. Onun için mesela ben Dart kullanmıştım, Dart'a merak salmıştım o zamanlar. Sen Dart, Swift, Kotlin, Flutter vs. bilmiyorsan korkmana gerek yok; bunları "hiçbir satır kod yazmadan" yapabileceğin web hizmetleri mevcut. (bkz: kodular.io, figma) Ayrıca göz atmak istersin diye o bahsettiğim projemin Youtube videosunu da buraya bırakacağım. (bkz: https://www.youtube.com/watch?v=PrDG0fbkqMU)

Belki projeyi daha da ileri taşırsan Raspberry Pi veya Arduino kart ile akıllı ev projesine bile dönüştürülebilir, aynı Jarvis gibi bir şey yapabilirsin. Tabii bunlar işin teferruatları, şimdilik elindeki kodu geliştirmeye bakmalısın :)

Kodu yazış şekline gelicek olursam ilk başta bu tarz yapay zeka işleri için hangi dilin öncü olduğunu büyük ihtimalle biliyorsundun (Python). Bundan dolayı Python programlama diliyle bu tarz şeyleri yapmak çok daha kolay olur senin için, discord botlarını da Python ile yapabilirsin hem de (D.js kadar gelişmiş olmasa da). Onun dışında if statementler için Curly Braces denen "{}", bu arkadaşlardan kullanmamana sevindim; çünkü yalnızca tek bir şey yapacağız ve buna gerek yok. Tabii bu şekilde de kodu okumak biraz zorlaşmış ama kişisel görüşümce Javascript programlama dilini bilen çoğu kişi bunu rahatlıkla yorumlayabilir, geliştirebilir, okuyabilir. Onun dışında "var m" kısmındaki "m" değişkeninin neye karşılık geldiğini anlamada biraz sorun yaşadım başlangıçta, daha anlaşılır ve uzun bir şey kullanabilirsin; mesela "message, input, usermsg, msg vs." 

Kısacası demek istediğim, güzel bir iş çıkarmışsın tebrikler :) Yalnızca kullandığım programlama dilini değiştirebilirsin, Python bilmiyorsan sana öğrenmende yardımcı bile olabilirim istersen, ve de kodunu biraz daha açık (clean) yazabilirsin.

Clean Code hakkında detaylı bilgi edinmek istiyorsan; "https://www.youtube.com/watch?v=0iF0RWSCcxM&list=PLxw2ybf4zPJ5TncW4_IWqFSGGybTaXs5I" bu oynatma listesi işine yarayabilir.

**Comment by InFlames513** [comment]
> Öncellikle fikrinden başlamak istiyorum, fikrin gayet güzel ve uygulanabilirliği yüksek. Bunu geliştirmek için belki bir sanal asistana bağlayabilirsin. Microsoft'un Cortana'sı, Amazon'un Alexa'sı, Google'ın Asistan'ı gibi asistanlar oluşturabilirsin kendine. Büyük ihtimalle "bu da yapay zeka mı ya" diyen ve yapay zeka hakkında gram bir şey bilmeyenler çıkacaktır projene yorum yapanlar arasından. Tabii sen bu "insancıklara" çok önem vermemen gerekiyor, yapay zekayı gerektiği kadar içeren bir proje olduğundan emin olabiliriz, konuyu az da olsa bilen birisi de zaten bu yorumu rahatlıkla yapabilir.
> 
> Mesela şöyle bir şey yapabilirsin. Bu soru ve cevapların her biri veritabanında saklansın, oradan bu verileri çekelim. Veritabanı dediğimde irkilmene gerek yok, NoSQL olan bir veritabanı fazlasıyla işini görecektir (bkz: Google Firebase Realtime Database). Onun dışında bunu yapmana da gerek yok. Kendin JSON dosyası oluşturup, veri tabanı olarak kullanabilirsin. Ben bunu LUA üzerinde yapmıştım electraDB adı altında ve gayet de kullanılabilir halde şu anda.
> 
> Ayrıca mesela bir kullanıcı "nasılsınız" dedi, başka biri geldi "naber la" dedi başka biri de geldi "nörüyon" dedi. Bunların her birini kullanıcı dediğinde Data Training mantığı adı altında eğiterek yapay zekanın isabetliğini artırabilirsin. (bkz: https://www.youtube.com/watch?v=x2mRoFNm22g)
> 
> Onun dışında bunu bir bot haline getirebilirsin veya dediğim gibi sanal asistan haline getirebilirsin. Sanal asistan haline getirirsen ve mobil cihaz desteği vs. yaparsan çok iyi olabilir. Mesela kullanıcı mobil cihazını bilgisayarla eşleştirdikten sonra mobil cihazı üzerinden bilgisayar işlemleri yapabilsin. Ben buna benzer bir şeyi yapmıştım aslında. Telefonla bilgisayarı eşleştirip, telefon uygulaması üzerinden "yalnızca konuşarak" istediğimiz veya rastgele bir şarkının Spotify Windows aplikasyonu üzerinde çalmasını sağlayabiliyorduk. Onun için mesela ben Dart kullanmıştım, Dart'a merak salmıştım o zamanlar. Sen Dart, Swift, Kotlin, Flutter vs. bilmiyorsan korkmana gerek yok; bunları "hiçbir satır kod yazmadan" yapabileceğin web hizmetleri mevcut. (bkz: kodular.io, figma) Ayrıca göz atmak istersin diye o bahsettiğim projemin Youtube videosunu da buraya bırakacağım. (bkz: https://www.youtube.com/watch?v=PrDG0fbkqMU)
> 
> Belki projeyi daha da ileri taşırsan Raspberry Pi veya Arduino kart ile akıllı ev projesine bile dönüştürülebilir, aynı Jarvis gibi bir şey yapabilirsin. Tabii bunlar işin teferruatları, şimdilik elindeki kodu geliştirmeye bakmalısın :)
> 
> Kodu yazış şekline gelicek olursam ilk başta bu tarz yapay zeka işleri için hangi dilin öncü olduğunu büyük ihtimalle biliyorsundun (Python). Bundan dolayı Python programlama diliyle bu tarz şeyleri yapmak çok daha kolay olur senin için, discord botlarını da Python ile yapabilirsin hem de (D.js kadar gelişmiş olmasa da). Onun dışında if statementler için Curly Braces denen "{}", bu arkadaşlardan kullanmamana sevindim; çünkü yalnızca tek bir şey yapacağız ve buna gerek yok. Tabii bu şekilde de kodu okumak biraz zorlaşmış ama kişisel görüşümce Javascript programlama dilini bilen çoğu kişi bunu rahatlıkla yorumlayabilir, geliştirebilir, okuyabilir. Onun dışında "var m" kısmındaki "m" değişkeninin neye karşılık geldiğini anlamada biraz sorun yaşadım başlangıçta, daha anlaşılır ve uzun bir şey kullanabilirsin; mesela "message, input, usermsg, msg vs."
> 
> Kısacası demek istediğim, güzel bir iş çıkarmışsın tebrikler :) Yalnızca kullandığım programlama dilini değiştirebilirsin, Python bilmiyorsan sana öğrenmende yardımcı bile olabilirim istersen, ve de kodunu biraz daha açık (clean) yazabilirsin.
> 
> Clean Code hakkında detaylı bilgi edinmek istiyorsan; "https://www.youtube.com/watch?v=0iF0RWSCcxM&list=PLxw2ybf4zPJ5TncW4_IWqFSGGybTaXs5I" bu oynatma listesi işine yarayabilir.

Yazını tamamen okudum bende bu kodu sesli asistanımda kullanmayı düşünüyorum ve database kısmını bende yapmayı düşünüyorum gerçek bir yapay zeka olmasını istiyorum pythondan daha kolay olur evet fakat çok fazla python bilgim var mesela bu kodu pythonda yazabilirim ama ilerde başka şeyler yaparken büyük ihtimal sorun yaşayacağım için bunu javascript ile kodladım ama pythona geçirmeyi düşünüyorum.

Telefondan bilgisayara sesli komut ile işlemler yaptırma fikrin hoşuma gitti bunuda ilerde mobil app yaparsam ekleyeceğim proje Jarvis gibi bir robot olur mu onu bilemem ama ben geliştirmeye devam edeceğim eğer birileri kötülerse sevinirim çünkü ben eğer birileri beni kötülüyorsa bir şeyler başarmaya başlamışımdır diye düşünüyorum.

**Comment by furkanesenn** [comment]
Evet, haklısın 👍.  Herhangi bir konuda sormak veya fikir almak istersen buradan veya Discord platformu üzerinden ulaşabilirsin :)

Discord -> violence#7034
