### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Venom1881** [InFlames513/basit-yapay-zeka-apisi#2]
Bu projeyi python ile sesli asistan modülünede uyarlayabilir miyiz ayrıca database kullanarak kodun yeni cevaplar öğrenmesini saglayabilir miyiz mümkün mü acaba?

**Comment by InFlames513** [comment]
Evet tabiki eğer pythona geçirirseniz zaten çok daha sağlıklı olur ayrıca sesli asistan ilede kullanabilirsiniz oradada örnek hazır cevapları mevcut database kullanarak kelime öğretmek istiyorsanızda json gibi yavaş db ler tercih etmezseniz yararınıza olur json çok çabuk dolar ve yavaşlar.

**Comment by Venom1881** [comment]
> Evet tabiki eğer pythona geçirirseniz zaten çok daha sağlıklı olur ayrıca sesli asistan ilede kullanabilirsiniz oradada örnek hazır cevapları mevcut database kullanarak kelime öğretmek istiyorsanızda json gibi yavaş db ler tercih etmezseniz yararınıza olur json çok çabuk dolar ve yavaşlar.

tamamdır teşekkürler ❤️

**Comment by Venom1881** [comment]
> Evet tabii ki eğer pythona geçerseniz zaten çok daha sağlıklı olur ayrıca sesli asistan ilede kullanabilirsiniz oradada örnek hazır cevaplar mevcut veritabanını kullanarak kelime yapılandırmak istiyorsanız json gibi yavaş db ler tercih etmezseniz kullanmanıza olur json çok dolar çabuk ve yavaşlar.

tamamdır teşekkürler.
